vich_uploader:
    db_driver: orm

    mappings:
        slider:
            uri_prefix: /assets/img/hero
            upload_destination: '%kernel.project_dir%/public/assets/img/hero'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: false
        article:
            uri_prefix: /assets/img/blog
            upload_destination: '%kernel.project_dir%/public/assets/img/blog'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: false
        service:
            uri_prefix: /assets/img/service
            upload_destination: '%kernel.project_dir%/public/assets/img/service'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: false
        profil:
            uri_prefix: /assets/img/profile
            upload_destination: '%kernel.project_dir%/public/assets/img/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: false
        specialite:
            uri_prefix: /assets/img/icon
            upload_destination: '%kernel.project_dir%/assets/img/icon'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: false
