vich_uploader:
    db_driver: orm

    mappings:
        slider:
            uri_prefix: /assets/img/hero
            upload_destination: '%kernel.project_dir%/public/assets/img/hero'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: false
