# CI vers planete hoster
name: CI
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSHPASS: ${{ secrets.PASS }}

    steps:
    - uses: actions/checkout@v2

    - name: Install and UPDATE sshpass
      run: 
        sudo apt-get update && sudo apt install sshpass

    - name: Deploy over SSH
      run:
        # ggcdqyct@node2-ca.n0c.com port 5022
        sshpass -e ssh -o StrictHostKeyChecking=no -p 5022 ${{ secrets.USER }}@${{ secrets.HOST }}
        "cd public_html"
 
